### ISSUE TITLE
I don't get any build output

### ISSUE THREAD

**Issue by hansfbaier** [pepijndevos/rust-litex-hal#20]
`cargo build --example counter` does not give me any executable in the `target/` tree.
Only a whole lot of libraries.

**Comment by pepijndevos** [comment]
Sorry not really sure what's going on here I think you may want to do 
https://github.com/pepijndevos/rust-litex-hal/blob/d7c24ebf42880671bc91e3d18f9dfaca2b4edd0c/Makefile.toml#L4

**Comment by Shatur** [comment]
You can't run examples through cargo. Examples are firmware that should run on the hardware or litex_sim. See the readme.

**Comment by pepijndevos** [comment]
Yes I think the confusing is just which commands are needed to generate firmware files and where they are stored.

IIRC indeed you get an .o file in the target folder, and you need objcopy to make a firmware file.
